version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser    # Adds a non-root user for security
      MYSQL_PASSWORD: pass123
      MYSQL_ROOT_PASSWORD: pass123
    networks:
      - sameNetworkAsMysql
    ports:
      - "3307:3306"  # Ensure your app is connecting to `db:3306`
    volumes:
      - mysql_data:/var/lib/mysql  # Persists database data
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql  # Executes script at startup
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_api
    restart: always
    depends_on:
      db:
        condition: service_healthy  # Ensures MySQL is ready before starting
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: appuser
      DB_PASSWORD: pass123
      DB_NAME: appdb
    networks:
      - sameNetworkAsMysql
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend_app
    restart: on-failure
    depends_on:
      - api
    networks:
      - sameNetworkAsMysql
    ports:
      - "3001:3000"

networks:
  sameNetworkAsMysql:
    driver: bridge

volumes:
  mysql_data:  # Persistent volume for MySQL data
